### ISSUE TITLE
prototype building different outputs (eg web and charter) from single codebase

### ISSUE THREAD

**Issue by vincelee888** [StreetSupport/streetsupport-web#202]
Spin up a quick prototype to build different outputs from the same codebase, with a view to merge the codebases of [the main site](https://github.com/StreetSupport/streetsupport-web), and the (the charter)[https://github.com/StreetSupport/manchester-charter].

pros:
* reduce code duplication across styles, common js modules

cons:
* complication in codebase and build

**Comment by fephil** [comment]
Pros:

* Stops charter being out of sync with technical updates
