### ISSUE TITLE
review webpack caching

### ISSUE THREAD

**Issue by vincelee888** [StreetSupport/streetsupport-web#203]
Not sure if webpack is caching stuff correctly when it chunks everything. can then get rid of our custom cache busting in the pipeline

**Comment by fephil** [comment]
I can provide some insight into this:

1. The idea was to chunk the JS into per page files. 
2. SSN is probably closer to a PWA than a group of pages (even though that is what it is).
2. To be honest, I wasn't as good with webpack as I am now so there have been mistakes made resulting in duplication of the code.

It can be fixed but it depends how you want to go about it. eg do we just build everything to an [output].js file and include it everywhere? I still like the idea of having separate JS files but it would need to be thought through.
