### ISSUE TITLE
add link to subscribe to mailchimp mailing list

### ISSUE THREAD

**Issue by vincelee888** [StreetSupport/streetsupport-web#204]
On the [contact page](https://streetsupport.net/contact/), add a button to subscribe to our monthly newsletter.

Add the button to the "more information" section.

link: http://streetsupport.us12.list-manage1.com/subscribe?u=da9a1d4bb2b1a69a981456972&id=52ba96f2af

**Comment by bnmrly** [comment]
Will look at when back in next week but let me know if you need sooner, cheers.

**Comment by bnmrly** [comment]
Here you go: https://github.com/StreetSupport/streetsupport-web/pull/211
