### ISSUE TITLE
reduce file size of header background image

### ISSUE THREAD

**Issue by vincelee888** [StreetSupport/streetsupport-web#41]
The image used for the header background image (https://charter.streetsupport.net/assets/img/header-background.png) is 70kb. Replace with a SVG.

this can also be ported to the charter: https://github.com/StreetSupport/manchester-charter/issues/9

**Comment by fephil** [comment]
This has been superseded by site updates

**Comment by vincelee888** [comment]
re-opening as it is used on generic pages

**Comment by bnmrly** [comment]
Will look at when back in next week but let me know if you need sooner, cheers.

**Comment by vincelee888** [comment]
i was thinking create the gradient in css, then tile a slightly transparent house shape in a png or svg
