### ISSUE TITLE
Fix print styling on organisation listing

### ISSUE THREAD

**Issue by vincelee888** [StreetSupport/streetsupport-web#418]
Improve use of space when printing the org listing page eg https://streetsupport.net/find-help/meals/timetable/ by adding print media query to the components:

* remove entire search box (titled "To find organisations in your area...")
* remove entire search organisation by name form
* remove view type tabs (list, map)
* remove drop shadow from card
* add print button underneath heading synopsis, giving it a class of .js-print-btn
* hide print button in print styling

**Comment by toshitapandey** [comment]
I'll take this on.

**Comment by szappacosta** [comment]
Hi @toshitapandey, i'm working on a similar issue : https://github.com/StreetSupport/streetsupport-web/issues/417. Waiting for @vincelee888 reply

**Comment by toshitapandey** [comment]
Ok, dropping it then.

**Comment by vincelee888** [comment]
@toshitapandey i have merged @szappacosta's PR (https://github.com/StreetSupport/streetsupport-web/commit/81fb447e0832139f880ae9930f6b1d382f9e7141) if you would like to review and carry on

**Comment by vincelee888** [comment]
superseded by https://github.com/StreetSupport/streetsupport-web/issues/453
