### ISSUE TITLE
Move heading to reduce extraneous white-space

### ISSUE THREAD

**Issue by vincelee888** [StreetSupport/streetsupport-web#419]
Move the heading "To find services near you, enter your postcode below." in the search box, to underneath the category heading.

Change the moved paragraph to "To find services near you, please enter your postcode"

Have a look at:

* https://github.com/StreetSupport/streetsupport-web/blob/develop/src/partials/find-help/header.hbs
* https://github.com/StreetSupport/streetsupport-web/blob/develop/src/partials/locations/selector-hogan.hbs

**Comment by kdavis-ssi** [comment]
I'll take this on.

**Comment by vincelee888** [comment]
thanks @kdavis-ssi !
