### ISSUE TITLE
Add link to donate directly to Street Support

### ISSUE THREAD

**Issue by vincelee888** [StreetSupport/streetsupport-web#421]
* Add link to https://www.justgiving.com/streetsupportnetwork in the "How you can help" section in https://github.com/StreetSupport/streetsupport-web/blob/develop/src/pages/give-help/partnership/index.hbs
* use class "btn btn--brand-e" for link, and "btn__text" for child span tag
* rename "partnership" directory to "business-support"
* add permanent redirect in web.config from "give-help/partnership" to "give-help/business-support"
* update any href links 
* update nav link text to "Business Support"
* update title to "Business Support"
* update sub-title to "How your business can help"

**Comment by gargshruti30** [comment]
@vincelee888 Can I work on this issue ?

**Comment by vincelee888** [comment]
hi @gargshruti30. yes please!

**Comment by vincelee888** [comment]
cheers @mikecoram !
