### ISSUE TITLE
wire up organisation search to API endpoint

### ISSUE THREAD

**Issue by vincelee888** [StreetSupport/streetsupport-web#422]
on the org listing page (find-help/all-service-providers/) wire up to the search org form to query the API (currently, it just does a client-side filter of the orgs returned by the postcode proximity search)

this requires a GET request being sent to the API endpoint via the following URL: /v1/service-provider-locations/?name={org-name}

**Comment by mikecoram** [comment]
I'll take this one 👍

**Comment by mikecoram** [comment]
Just a quick update: I've managed to get this working on my branch cec4100 but it's broken the search unit tests, so I need to work out how to fix those before I can put in the pull request.

**Comment by vincelee888** [comment]
@mikecoram - you should be able to just delete the failing tests, and copy and amend the existing ones for the listing (spec\find-help\all-organisations\HappyPathSpec.js). the main tests are that it:

* on search, it makes the correct request with expected querystring to the API
* it replaces any previously retrieved items by the results of the search
* the load more still works, should there be more than size items that match the search query

**Comment by mikecoram** [comment]
My apologies, I haven't managed to finish this and can't make it tonight. 

Anyone should feel free to pick this up, my changes are here: https://github.com/mikecoram/streetsupport-web/tree/search-by-name

**Comment by vincelee888** [comment]
thanks @mikecoram. i've merged that in and fixed the test.
