### ISSUE TITLE
Add link to Bournemouth JustGiving page, from bournemouth nav

### ISSUE THREAD

**Issue by vincelee888** [StreetSupport/streetsupport-web#458]
link text "Donate Now"

edit https://github.com/StreetSupport/streetsupport-web/blob/develop/src/partials/bournemouth/nav.hbs

link: https://www.justgiving.com/campaign/changeforgoodBournemouth

**Comment by joseph-allen** [comment]
https://github.com/StreetSupport/streetsupport-web/pull/463
